### ISSUE TITLE
Eliminate unneeded second grand final in some cases

### ISSUE THREAD

**Issue by seiyria** [clux/duel#12]
Hi!

So, some users have reported to me that in one specific case, the second grand final match is not necessary -- this happens when a player from the winners bracket wins the first grand final. I'm not sure if this is covered entirely by the `short` option, but is this a desirable addition to the base library? If so, that'd be fabulous!

Thanks!

**Comment by clux** [comment]
That is what `short` does in double elimination. In single elimination it controls the bronze final.

The second grandfinal is deliberately left empty if (and only if) the WB winner wins GF1.

With `short` enabled, you never get GF2 - which is unfair as the loss to get into LB doesn't mean anything, but at least the tournament has deterministic length.

**Comment by clux** [comment]
You probably want to hide GF2 until it actually `isPlayable()`

**Comment by seiyria** [comment]
I see! That's a bit of special magic though, to detect whether or not it's playable (as opposed to everything else, that is, because they're all handled the same way).

Hmmm. I might be able to logic it, though, as I've noticed from the users screenshot (see [here](http://i.imgur.com/nVZVwEh.png?1)) that the tournament itself is noted as complete. I think I can hide all unplayed matches if the tournament is complete and call it good there. Thank you for the quick response as always, it helps get my mind jogging on these issues (and it kicks it back at me, so I know it's something I can fix)!

**Comment by clux** [comment]
Yeah, that is special magic, but it had to go somewhere. You may find it useful to know that it's always the last match in double elimination if `!short` because of how matches are sorted in scorable order.
