### ISSUE TITLE
Meet Twice

### ISSUE THREAD

**Issue by SeVeNDuS** [clux/duel#14]
Hi,

Spanish Cup have all rounds, except the final, the meetTwice options, so the round winner depends on two matches.

Could be possible to add those configurations?

- meetTwice and if yes, final in single match

Regards

**Comment by clux** [comment]
Hm, never heard of this format. Got any example links? Not sure I fully understand.

There's the double final in double elimination which you can set with the `short` flag, but this sounds different.

If it is just two matches where a normal match would be, you could also handle it outside `Duel` and call `trn.score` with the sum of the results where appropriate.

**Comment by SeVeNDuS** [comment]
Maybe I have explained myself in a wrong mode.

The way I want it's like the final stage (after group stage) of UEFA Champions League.

I mean, all matches except the final are played twice. Spanish Cup is played in that way all the tournament.

Example for 4 teams A, B, C, D

A vs B
Match 1: 1 - 0
Match 2: 0 - 2
B goes to second round

C vs D
Match 1: 0 - 0
Match 2: 1 - 0
C goes to second round

Final:
B vs C
Result: 1 - 0
B wins the tournament

In this case we need to manage ties with some rules, most common (in football) is the goals scored away

Regards

**Comment by clux** [comment]
Okay. Yes, I see what you mean now. The current advice on these kinds of things is to just treat is as a normal Duel tournament and pass down the decider itself. Duel does not really deal with these specifics like goals. All it got is a score array, and it's not meant to be much smarter than that. It just got the progression logic.

In your case you should score the first semi final with A-vs-B as [0,1] (passing down match wins), and the other semi final with C-vs-D as [1,0].

If you require more information or more specific tie handling by counting goals and other statistics (if goals fail to decide), you would need logic on top of Duel to handle richer score data, and invent some sensible numbering to pass on to `trn.score` (you wouldn't even have to display these values in your user interface). This is outside the scope of this library, but it can be done.

**Comment by SeVeNDuS** [comment]
My request was more like reporduce the meetTwice parameter that you have in groupStage more than prepare a kind of tiebreaker that I understand that it's very specific

Regards

**Comment by clux** [comment]
Oh. Right. Yes, that would perhaps be possible.

FFA already has TieBreaker integration to basically handle a tie case in a very similar way, but that's a quite heavyweight solution. Don't really want to chain two player groupstage instances each round (with meetTwice set), then pass that through TieBreaker just to get this feature (although that would be one solution to what you describe by using tourney).

But if we're not doing that, then we'd have to implement quite a bit of tiebreaker logic into Duel just for this. I'm not really sure it's worth it. A wrapper library feels a lot more sane for this kind of problem, mostly because it doesn't try to cram to much into an already complicated library - and it would have the option of handling match data in a more specific, and more general way than what tiebreaker is doing. You are already at the level where you are designing for a sport it sounds like.

Not ruling this out, but gonna have to think about this for a while.

**Comment by SeVeNDuS** [comment]
My idea is more for an e-sport tournament where players play same games against other and got scores, For example, Ghost Recon number of kills, or something like that; or a fantasy football where the user get points more than goals.

The special tiebreaker is not important for me due to I can manage that logic out of your library, the "problem" is that I need to have something where store that partial scores to can do the tiebreak (if needed).

Have you see my edited comment? If not, I put it below

A possible way to handle it without a lot of effort could be have a method addTempScore(score) or something similar that add that score to an array of temp scores. Then, this could be used to can get the final score [1,0] or [0,1] from outside the duel package.

What do you think?

Regards

**Comment by clux** [comment]
I understand, yeah, I did not consider the intermediate state saving issue. Thanks for pointing out the edit.

Adding a temporary scoring method is probably still too low level for what I want in tournament/duel, as this is not really a core mechanic for most tournaments, and it could interfere with progression mechanics of other tournaments.

However, I have [mandated that tournaments keep the `data` key on a match clean](https://github.com/clux/tournament/blob/427d3c25dd7cb2ffc40ed3b702fb81e9e46af05b/doc/implementors.md#matches). I think if you set your temporary data on each match like `match.data = { tempScore: [0,1] }`, then that would be sufficient for your use.

The only problem with that the data is not really saved along with the normal state. I.e. if you use `Duel.restore` from database step as per https://github.com/clux/tournament/blob/427d3c25dd7cb2ffc40ed3b702fb81e9e46af05b/doc/base.md#serialization then this data is lost if you store it on the match. This feels like it should be supported, and it would allow you to solve your problem.

How do you feel about that?

**Comment by clux** [comment]
Cool. I'll have a look at that soon :)
Thanks for reporting this.

**Comment by SeVeNDuS** [comment]
Thank you very match ;)

**Comment by clux** [comment]
This should now work, see referenced issue for details.
