### ISSUE TITLE
Conflict Issue.

### ISSUE THREAD

**Issue by masihur** [clux/duel#15]
Hi,

I have a page where I used a forum within iframe, iframe resized dynamically using iframe resizer.
IF I used duel.js file before it then iframe resizer script then iframe resizer is not working while if I used
duel.js after iframe resizer script then it's working fine.

Please suggest.

**Comment by clux** [comment]
Sounds like an issue with your resizer, or how you load/bundle modules.

How to load modules is not really something I can/want to solve here for you. Take a look at browserify / webpack for these things.
