### ISSUE TITLE
any possibility of bower installation for all of these?

### ISSUE THREAD

**Issue by seiyria** [clux/duel#7]
basically it would just be the bundled stuff in each of the respective tournament packages. would be much nicer for those of us that are avoiding browserify.

**Comment by clux** [comment]
No, sorry. These modules are developed together with the intention that they work together sensibly with npm dedupe and browserify. But putting the browserify step into every tournament module just so apps can avoid it is poor software development.

**Comment by seiyria** [comment]
Not everyone has the same workflow. 

In this case, I'd even be fine with a separate repo that just includes all of them and makes them all easily importable. It's definitely not poor software development, because literally every popular library makes it easy to install+include dependencies and just get up and running with them, while still keeping them under version control. Doing as you suggest means that anyone who uses your utilities has to add an extra step, and unless they're using browserify, they can't keep your stuff under version control -- they'd need to keep a `vendor` folder, or something. I also don't like checking my dependencies into version control, so that pretty much breaks that idea.

**Comment by seiyria** [comment]
For those that come across this in the future, I've set up a bower installation here: https://github.com/seiyria/tournament-bower

**Comment by clux** [comment]
A lot of what you are saying is sensible, but ultimately:

> unless they're using browserify, they can't keep your stuff under version control

This is commonjs, if you are unwilling to transform commonjs into something browser compatible in 2015, you're going to have a bad time. Package.json for deps like these that do not have bower.json, and a one line compile step is not an unreasonable request. No need to check in dependencies, and it's one extra line. 

Say I add browserify (or any other commonjs bundler) to my modules to produce the output. You will still depend on browserify, only now it's an implicit dependency and you cannot change its version. If you depend on multiple libraries that are pre-browserifying, then you are relying on multiple versions of browserify.

**Comment by clux** [comment]
Ah, yes. I have no problem with any solution like that. As long as you have some way of testing it. I don't have time to test browserify versions against every library, but if this keeps it out of your app in the way you want then great!
