### ISSUE TITLE
how do I know what match is next?

### ISSUE THREAD

**Issue by seiyria** [clux/duel#8]
Suppose I have a 5 player single elimination tournament:

![](http://puu.sh/kx8jB/c4c1a19e26.png)

0 and 1 have to face off first to determine who can face 4. How do I know what the next match for 0 and 1 is? I want to draw a line between them.

I've tried `duelInst.right(0)`, `duelInst.down(0)`, and `duelInst.upcoming(0)` (as well as for 1), but none of these seem to give me the `id` of the next match. Did I miss something?

**Comment by clux** [comment]
Player ids start at 1, not sure how you got zero, this is probably why `duelInst.upcoming(playerId)` is failing.

`down` and `right` are helpers that you can use if you are confident, but they take a match id. If you pass down or right `duelInst.matches[0].id` instead, you should get something sensible.

**Comment by clux** [comment]
Oh, yeah, zero is the marker for a match that is not filled in yet. It's not a real player. That match is waiting for a match in an earlier round.

**Comment by clux** [comment]
Not quite sure how you got that representation of a Duel though. A 5 player duel should have 4 matches in round 1 (s:1, r:1), two of which are walkovers (m1 and m3).

```js
(new Duel(5)).matches;
[ { id: Id { s: 1, r: 1, m: 1 }, p: [ 1, -1 ], m: [ 1, 0 ] },
  { id: Id { s: 1, r: 1, m: 2 }, p: [ 5, 4 ] },
  { id: Id { s: 1, r: 1, m: 3 }, p: [ 3, -1 ], m: [ 1, 0 ] },
  { id: Id { s: 1, r: 1, m: 4 }, p: [ -1, 2 ], m: [ 0, 1 ] },
  { id: Id { s: 1, r: 2, m: 1 }, p: [ 1, 0 ] },
  { id: Id { s: 1, r: 2, m: 2 }, p: [ 3, 2 ] },
  { id: Id { s: 1, r: 3, m: 1 }, p: [ 0, 0 ] },
  { id: Id { s: 2, r: 1, m: 1 }, p: [ 0, 0 ] } ]
```

**Comment by seiyria** [comment]
Sure enough - I thought they corresponded with array indexes, which is why I was confused. I am getting a seemingly correct result if I check for `upcoming(1)`. My duel representation is: 

```
[
{"id":{"s":1,"r":1,"m":1},"p":[1,-1],"m":[1,0]},
{"id":{"s":1,"r":1,"m":2},"p":[5,4]},
{"id":{"s":1,"r":1,"m":3},"p":[3,-1],"m":[1,0]},
{"id":{"s":1,"r":1,"m":4},"p":[-1,2],"m":[0,1]},
{"id":{"s":1,"r":2,"m":1},"p":[1,0]},
{"id":{"s":1,"r":2,"m":2},"p":[3,2]},
{"id":{"s":1,"r":3,"m":1},"p":[0,0]}
]
```

... which is the same as yours. I've just hid the unnecessary matches (I'm not certain it's necessary to show them).

Thanks!

**Comment by seiyria** [comment]
I know you have a note about `duel.down` and `duel.right` not returning properly in some cases. With my loser bracket, they are giving strange results (note that all the normal bracket stuff, ie, `right`, is working properly): 

![](http://puu.sh/kzLCF/94e7a6995c.png)

Any idea why it's reporting the wrong ones for `down`?

**Comment by clux** [comment]
`down` should be returning correctly - it is heavily tested. That said, it may be a bit counter intuitive in that it is designed so that the losers bracket moves up to meet the winner bracket winner. If you have any examples, I can have a look.

**Comment by seiyria** [comment]
Yeah - you're right. I wanted to check if there was something on your end that you knew about, but it turns out that those first matches have a circular reference when they do `down` (ie, `2-A -> 2-A`), but when I disabled that, it made a bit more sense.

**Comment by seiyria** [comment]
Okay, so I'm having some problems that I don't quite get. Some of your variables are a bit cryptic and I couldn't discern their meaning from the code here.

Here's what a bigger tournament looks like:
![](http://puu.sh/kzSgv/0476fc52d0.png)

After I score 1-G ("blerg vs test"), blerg loses, and goes to 2-D and 2-H.

![](http://puu.sh/kzShE/205e831578.png)

I'm trying to figure out how to detect cases like this, where 2-D essentially goes straight to 2-H. I could render everything, including the walkover rounds, but that creates some unnecessary noise IMO. I noticed you have a `p` variable but I can't figure out how or why it's used, and I suspect that might have something to help me.

**Comment by clux** [comment]
Yeah, double elimination is not always pretty when the number of players is not a perfect power of two. In extreme cases you can have entire matches in loser bracket round 1 have double walkover markers (the [-1, -1] in LBR1 you sometimes see). The number of matches is always a function of the nearest power of 2, so they are always included but you can safely ignore those matches.

The [-1, 0] case happens when a WO marker is in a match, but the dependent match has not filled it in. As soon as the zero get updated with the player that moves there, it will make sense and the player will immediately win and move right.

**Comment by clux** [comment]
Note that completely useless matches with a double WO marker are only created at instantiation. They can only happen in LBR1. WO markers otherwise can happen in WBR1 and LBR2, but after that there's guaranteed to be two players.

**Comment by clux** [comment]
You are right that the variable abbreviations are always helpful. There's even cases where two one letter variables are used synonymously before terminology was fully decided, like m and g for match number and game number respectively, or b and s for bracket or (more generally) section. Should probably clean that up.

**Comment by seiyria** [comment]
I'd really appreciate that! I plan to make use of your full suite of tournament tools - so far, they seem very well done (minus the hiccups you've been hearing about from me the last few days). Very good job overall on these, and I appreciate your responsivity!

**Comment by clux** [comment]
That's great. I'd be interested to see how your openchallenge repo works out. Thanks a lot. Feel free to raise issues as you please, don't normally get that many people who use these libraries as they are very specialized - and when they do, it's typically in a very simple setting.

**Comment by seiyria** [comment]
Thanks! So far it's going very well. I think what I'm doing will be complex _enough_ , but before saturday, I had no idea about all of the stuff behind tournament brackets, so I'm still learning this stuff. That said, the utility you have here is relatively easy to figure out, except these edge cases :D

**Comment by seiyria** [comment]
Okay, I've finally nearly got this sorted out. I have a few problems with DE still, towards the ends of the tournament. So I have a DE tournament with 10 people, not short. This results in a set of matches across 8 rounds. However, the final match of the winner bracket as well as the last 4 matches in the loser bracket are reporting incorrect next-round points (I think).

My winner bracket is reporting something in the loser bracket in round 9 (max I have is 8), and the final 3 matches report rounds 10, 12, and 14 respectively. This struck me as odd a while ago but I never really had to worry about it until now. What's up with that?

**Comment by clux** [comment]
Hm. You shouldn't get anything higher than round 8 in a 10 player. Both `down` and `right` are returning sensible things for me:

```js
var Duel = require('duel');
var d = new Duel(10, {last: Duel.LB});
console.log(d.matches);
d.matches.forEach(function(m) {
  var right = d.right(m.id) ? d.right(m.id)[0] : null;
  var down = d.down(m.id) ? d.down(m.id)[0] : null;
  console.log(m.id + ' has right: ' +  right + ' and dn: ' + down);
});
```

output:

```
[ { id: { s: 1, r: 1, m: 1 }, p: [ 1, -1 ], m: [ 1, 0 ] },
  { id: { s: 1, r: 1, m: 2 }, p: [ 9, 8 ] },
  { id: { s: 1, r: 1, m: 3 }, p: [ 5, -1 ], m: [ 1, 0 ] },
  { id: { s: 1, r: 1, m: 4 }, p: [ -1, 4 ], m: [ 0, 1 ] },
  { id: { s: 1, r: 1, m: 5 }, p: [ 3, -1 ], m: [ 1, 0 ] },
  { id: { s: 1, r: 1, m: 6 }, p: [ -1, 6 ], m: [ 0, 1 ] },
  { id: { s: 1, r: 1, m: 7 }, p: [ 7, 10 ] },
  { id: { s: 1, r: 1, m: 8 }, p: [ -1, 2 ], m: [ 0, 1 ] },
  { id: { s: 1, r: 2, m: 1 }, p: [ 1, 0 ] },
  { id: { s: 1, r: 2, m: 2 }, p: [ 5, 4 ] },
  { id: { s: 1, r: 2, m: 3 }, p: [ 3, 6 ] },
  { id: { s: 1, r: 2, m: 4 }, p: [ 0, 2 ] },
  { id: { s: 1, r: 3, m: 1 }, p: [ 0, 0 ] },
  { id: { s: 1, r: 3, m: 2 }, p: [ 0, 0 ] },
  { id: { s: 1, r: 4, m: 1 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 1, m: 1 }, p: [ -1, 0 ], m: [ 0, 1 ] },
  { id: { s: 2, r: 1, m: 2 }, p: [ -1, -1 ], m: [ 0, 1 ] },
  { id: { s: 2, r: 1, m: 3 }, p: [ -1, -1 ], m: [ 0, 1 ] },
  { id: { s: 2, r: 1, m: 4 }, p: [ 0, -1 ], m: [ 1, 0 ] },
  { id: { s: 2, r: 2, m: 1 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 2, m: 2 }, p: [ -1, 0 ] },
  { id: { s: 2, r: 2, m: 3 }, p: [ 0, -1 ] },
  { id: { s: 2, r: 2, m: 4 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 3, m: 1 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 3, m: 2 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 4, m: 1 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 4, m: 2 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 5, m: 1 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 6, m: 1 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 7, m: 1 }, p: [ 0, 0 ] },
  { id: { s: 2, r: 8, m: 1 }, p: [ 0, 0 ] } ]
WB R1 M1 has right: WB R2 M1 and dn: LB R1 M1
WB R1 M2 has right: WB R2 M1 and dn: LB R1 M1
WB R1 M3 has right: WB R2 M2 and dn: LB R1 M2
WB R1 M4 has right: WB R2 M2 and dn: LB R1 M2
WB R1 M5 has right: WB R2 M3 and dn: LB R1 M3
WB R1 M6 has right: WB R2 M3 and dn: LB R1 M3
WB R1 M7 has right: WB R2 M4 and dn: LB R1 M4
WB R1 M8 has right: WB R2 M4 and dn: LB R1 M4
WB R2 M1 has right: WB R3 M1 and dn: LB R2 M1
WB R2 M2 has right: WB R3 M1 and dn: LB R2 M2
WB R2 M3 has right: WB R3 M2 and dn: LB R2 M3
WB R2 M4 has right: WB R3 M2 and dn: LB R2 M4
WB R3 M1 has right: WB R4 M1 and dn: LB R4 M1
WB R3 M2 has right: WB R4 M1 and dn: LB R4 M2
WB R4 M1 has right: LB R7 M1 and dn: LB R6 M1
LB R1 M1 has right: LB R2 M1 and dn: null
LB R1 M2 has right: LB R2 M2 and dn: null
LB R1 M3 has right: LB R2 M3 and dn: null
LB R1 M4 has right: LB R2 M4 and dn: null
LB R2 M1 has right: LB R3 M1 and dn: null
LB R2 M2 has right: LB R3 M1 and dn: null
LB R2 M3 has right: LB R3 M2 and dn: null
LB R2 M4 has right: LB R3 M2 and dn: null
LB R3 M1 has right: LB R4 M1 and dn: null
LB R3 M2 has right: LB R4 M2 and dn: null
LB R4 M1 has right: LB R5 M1 and dn: null
LB R4 M2 has right: LB R5 M1 and dn: null
LB R5 M1 has right: LB R6 M1 and dn: null
LB R6 M1 has right: LB R7 M1 and dn: null
LB R7 M1 has right: LB R8 M1 and dn: LB R8 M1
LB R8 M1 has right: null and dn: null
```

Essentially the only weird cases here should be 

1. where loser of the first grand final game in round 7,  sometimes moves to grand final game to in round 8. But that's only if the player that came from LB actually won.
2. Where winner of WB final (round 4) actually moves right into round 7 LB (grand final).

**Comment by clux** [comment]
Btw, while you're debugging I'd recommend sticking to duel tournaments <= 8 players since they have about half the number of matches as the 16 player model you get with 10 :]

**Comment by seiyria** [comment]
You're right, and I'm glad you are. Granted I haven't fixed the issue but what you're showing me is replicable on my side. Times like these I wish some structures were easily made immutable! Thanks again.

**Comment by seiyria** [comment]
A-ha! Okay, so this was weird. I changed all of my function references to strings, and invoked them dynamically instead of using the stale function, and everything works now.

I used to have `$scope.nextRound = $scope.trn.right` and I would invoke it like `$scope.nextRound(match)`. This is what gave improper results! If I instead invoke it dynamically, it works like a charm. That was a really strange bug, but thanks for helping me think through it!

**Comment by clux** [comment]
Ah. Yes, `right` and `down` use instance properties, so they would likely fail in strange ways with an invalid or missing context. You could use `nextRound = trn.right.bind(trn)` and it should also work.
